language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t service-image -f Dockerfile.dev .

script:
  - docker run service-image npm run test -- --coverage

deploy:
  - provider: elasticbeanstalk
  - region: "us-east-2"
  - app: "node-app"
  - env: "Nodeapp-env"
  - bucket_name: "elasticbeanstalk-us-east-2-089417250341"
  - bucket_path: "node-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
