version: '3'
services: 
  backend:
    build: .
    environment: 
      MONGO_CONNECTION_STRING: mongodb://mongo/test
      PORT: 1337
    ports:
      - '1337:1337'
  mongo:
    image: mongo:4.4
    restart: always