version: '3'
services: 
  backend:
    build: .
    environment: 
      MONGO_CONNECTION_STRING: mongodb://mongo/test
      PORT: 80
    ports:
      - '80:80'
  mongo:
    image: mongo:4.4
    restart: always