version: '3'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment: 
      MONGO_CONNECTION_STRING: mongodb://mongo/test
    volumes:
      - /usr/app/node_modules
      - .:/usr/app/
    ports:
      - '1337:1337'
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'